### ISSUE TITLE
Curl Issue

### ISSUE THREAD

**Issue by sunscreem** [billythekid/PunkApi#1]
I'm trying this out using laravel + homestead. I'm getting a weird error from guzzle.

![screenshot-learning app 2016-10-16 10-45-17](https://cloud.githubusercontent.com/assets/7523595/19416646/c3f216f2-938d-11e6-95a5-a47f1a121e7f.png)

I've followed the tips on [this thread](https://laracasts.com/discuss/channels/general-discussion/curl-error-60-ssl-certificate-problem-unable-to-get-local-issuer-certificate) but no joy.

Unless you can think of anything really obvious I'll come back to it when I get some 'free time'.

**Comment by billythekid** [comment]
maybe put your actual API key in there?

Edit: sorry, this sounded flippant. Replied via email thinking it was an email from sunscreem directly (we're pals IRL) Anybody reading this, feel free to add your own pleasantries before this, genuine, suggestion.

**Comment by sunscreem** [comment]
Oh. Oh right. Yeah. That.

You should put that in your readme.

Oh. You did.

Oh.

Huh - okay - new Issue. The app should give you a friendly error message when users forget to add their API Key ;)

**Comment by sunscreem** [comment]
Still not working - despite my stupidity... Same error. I'll have another look later.

**Comment by billythekid** [comment]
Yeah the error would be different for a wrong API key, just thought it worth pointing out and hoped. I think this could be a homestead issue. Works OK on a vanilla Laravel on Valet for me. (Yes I know that's a cliché) If I have time tomorrow I'll spin up a Homestead box and test this out further.

**Comment by billythekid** [comment]
Rob, I'm going to close this as there's about to be an update to the API so the whole code will stop working soon enough, never mind cURL. I'll let you know next release so you can test again.
