### ISSUE TITLE
PunkAPI v2

### ISSUE THREAD

**Issue by sammdec** [billythekid/PunkApi#2]
Hi billythekid,

I have rewritten PunkAPI to make it faster, smaller in size and split into easier to manage chunks. Im looking at releasing it on 18th December. I have decided that as of the 18th December, v1 of the api will no longer work due to some unavoidable changes in the codebase.

So what does this mean for you? There a few key things that will need to be updated in your lib,

The root endpoint has changed to https://api.punkapi.com/
There is no longer any authentication on the app and will be relying on rate limits
Let me know if you need any help or clarification with anything, everything else is the same

Thanks
Sam

**Comment by billythekid** [comment]
Cheers for the heads up Sam. I'll get around to updating to match as soon as I can.

**Comment by sammdec** [comment]
For your reference when you are ready to start work, here is the staging api V2: https://punkapi-server-yvudxdwnze.now.sh/

and the new docs: https://punkapi-site-mspadgyyyl.now.sh/ 👍

**Comment by sammdec** [comment]
Quick update about this, I have just been toying around with building  a proxy to keep the v1 api alive for a little bit longer and give people chance to migrate across, without breaking current apps.

Therefore, the official launch date of V2 of the api will still be the **18th December**, but I will also be keeping open v1 of the api until **15th Feburary 2017**.

Due to this I will also update the root endpoint which will now be `https://api.punkapi.com/v2`, here is an updated url which has these changes applied: https://punkapi-server-ivfgmegqyw.now.sh

**Comment by billythekid** [comment]
Cheers Sam, 

Finally got round to updating this for the new endpoint. 👍
